language: ruby

before_install: gem install bundler

rvm:
  - 2.2
env:
  - DB=postgresql
script:
  - bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
  - bundle exec rspec
  - bundle exec rubocop
before_script:
  - bundle exec rake db:create RAILS_ENV=test


matrix:
  # fast_finish will prevent allowed failed process from delaying build
  fast_finish: true
